updated yml file

diff --git a/.github/workflows/api-framework.yml b/.github/workflows/api-framework.yml
--- a/.github/workflows/api-framework.yml
+++ b/.github/workflows/api-framework.yml
@@ -29,13 +29,20 @@ jobs:
     - name: Set PYTHONPATH
       run: echo "PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE" >> $GITHUB_ENV
 
+    - name: Set environment variables
+      run: echo "API_TOKEN=${{ secrets.API_TOKEN }}" >> $GITHUB_ENV
+
+    - name: Verify config file exists
+      run: |
+        if [ ! -f resources/config.cfg ]; then
+          echo "Config file not found!"
+          exit 1
+
     - name: Create reports directory
       run: mkdir -p ./reports
 
-    - name: Run tests with API Token
+    - name: Run tests
       run: pytest -v --html=./reports/report.html
-      env:
-        API_TOKEN: ${{ secrets.API_TOKEN }}
 
     - name: Upload test report
       uses: actions/upload-artifact@v4
